## Introduction to object oriented programming in python
...
One of the popular approach to solve a programming problem by creating an objects.This is known as object oriented programming

<br>
An object has two characteristics:<br>
 1.attributes (name,age,color)<br>
 2.behaviour (learn,study,singing,dance)<br>
 
 In python ,the concept oop follow these things<br>
  1.Inheritance<br>
  2.Encapsulation<br>
  3.ploymorphism<br>
  
 class: 
       class is a blueprint for the object<br>
  object:
       Blue print of class or Instance of class or physical entity<br>
   constructors:
       part of class and can be called auotmatically 
  

class className:
    # some functions and variables
    # function -- used to perform the specific activity
    # Variables -- Data(memory)

In [2]:
def test():
    print('Test() for function')
    return
test()

Test() for function


In [3]:
class Demo:
    def test(self):
        print("test() for the class and method" )
        return
obj = Demo()
obj.test()

test() for the class and method


In [9]:
class Demo1:
    def fact(self,n):
        #return the factorial
        fact=1
        while(n!=0):
            fact = fact * n
            n = n - 1
        return fact
p1 = Demo1()
print(p1.fact(5))

120


In [12]:
class Demo2:
    
    def accept (self,p1,p2):
        a=p1
        b=p2
        return
    def display(self,p1,p2):
        print("p1= ",p1)
        print("p2= ",p2)
c1=Demo2()
c1.accept(10,20)
c1.display(10,20)

p1=  10
p2=  20


In [14]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
        
    def add(self,p1,p2):
        return p1+p2

c1=Demo2(10,20)
print(c1.add(100,200))

300


In [32]:
# Some inheritance
# Parent Class
class Person(object):
    # Constructor
    def __init__(self,name):
        self.name = name
    def getName(self):
        return self.name
    def isEmployee(self):
        return False
# Derived Class
class Employee(Person):
    def isEmployee(self):
        return True
    
emp = Person("Praneetha")
print(emp.getName(),emp.isEmployee())

emp1 = Employee("Sunayana")
print(emp1.getName(),emp1.isEmployee())

    

Praneetha False
Sunayana True


In [30]:
lst=[1,2,3,4]
print(lst)

[1, 2, 3, 4]


In [31]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [34]:
lst =[1.9,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
float64


In [37]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [38]:
# Re-shape the given array
# numpy.reshape(arrayName,reshape,order='C')
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
# Append some Data -- Horizontally
# hstack(array1,array2) -- will be automatically arranged in horizontally

a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [41]:
# Append some Data -- vertical
# vstack(array1,array2) -- will be automatically arranged in vertically
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))


[[1 2 3]
 [4 5 6]]


In [44]:
# Generate random number from np
a1=np.random.normal(5,0.5,10)
print(a1)

[5.09986016 5.21592482 4.58843905 4.29450164 5.1809135  5.53922739
 5.51617709 5.00558402 5.46286966 4.69557072]


In [45]:
# numpy.zeros() and numpy.one()
# Generate an array with all zeros -- numpy.zeros()
# numpy.zeros(shape,dtype=float,order=;c)
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [48]:
np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]], dtype=int64)

In [49]:
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [54]:
A =np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2] = 5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [55]:
A =np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3] = 14
np.asarray(A)[3][3] = 16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [56]:
# arrange () -- particular
# numpy.arrange(start,end,step)
# start -- value
# end -- value
# step -- gap b/w one value to another value

import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [60]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [68]:
# Indexing and slicing of numpy
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [64]:
a1=np.array([(1,2,3),(4,5,6)])
print("First row : ",a1[0])

First row :  [1 2 3]


In [67]:
a1=np.array([(1,2,3),(4,5,6)])
print("Second row : ",a1[1][1])

Second row :  5


In [65]:
a1=np.array([(1,2,3),(4,5,6)])
print("Slicing column : ",a1[:,1])

Slicing column :  [2 5]


In [66]:
a1=np.array([(1,2,3),(4,5,6)])
print("Slicing Last column : ",a1[:,2])

Slicing Last column :  [3 6]


In [69]:
a1=np.array([(1,2,3),(4,5,6)])
print("Row and column : ",a1[2:1])

Row and column :  []


In [70]:
a1 = np.random.normal(5,1,10)
print(a1)

[6.48413018 5.22339354 4.97557624 5.20740216 4.2877686  5.50790741
 3.93492735 5.37121197 3.35051239 5.29499808]


In [71]:
# some math operation on given random numbers
# Min   --- returns the least number
# Max   --- returns the large number
# Mean  --- mean
# Median -- median
a1 = np.random.normal(5,1,10)
print(a1)
print("Min value= ",np.min(a1))
print("Max value= ",np.max(a1))
print("Mean value= ",np.mean(a1))
print("Medin value= ",np.median(a1))



[4.92980796 5.1938046  5.70543175 3.39416791 6.2038819  3.75328326
 5.52978251 6.3365222  3.67218541 6.00188127]
Min value=  3.3941679121724944
Max value=  6.336522203754514
Mean value=  5.072074877798426
Medin value=  5.361793556555779


In [73]:
# Multiply of 1D arrays
# numpy.dot(x,y) -- output of multiplication

c1 = np.array([1,2])
c2 = np.array([3,4])
np.dot(c1,c2)

11

In [74]:
c1 = np.array([(1,2),(3,4)])
c2 = np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

## Pandas Basics

python is one of the popular programming language for data analysis<br>

python is offering the Lib called pandas used for importing and analyzing pretty much faster and easier also<br>

Pandas DataFrames
    Data Analysis With python

In [79]:
import pandas as pd
dict = {"Name":["Praneetha","Sunayana","Ravallika"],
       "EmailID":["praneethamadala01@gmail.com","ksunayana0@gmail.com","ravallika91@gmail.com"],
       "Mobile number":[93810,67301,89654],
       "Address":["Hyd","Hyd","Hyd"]}
b = pd.DataFrame(dict)
print(b)

        Name                      EmailID  Mobile number Address
0  Praneetha  praneethamadala01@gmail.com          93810     Hyd
1   Sunayana         ksunayana0@gmail.com          67301     Hyd
2  Ravallika        ravallika91@gmail.com          89654     Hyd


In [82]:
b.index = ["1","2","3"]
print(b)

        Name                      EmailID  Mobile number Address
1  Praneetha  praneethamadala01@gmail.com          93810     Hyd
2   Sunayana         ksunayana0@gmail.com          67301     Hyd
3  Ravallika        ravallika91@gmail.com          89654     Hyd


In [84]:
# Supermarket.csv - Analysis(Which product having higher % of selling)
# Which products having least selling %

import pandas as pd
products = pd.read_csv('FileName.csv')
print(products)

FileNotFoundError: [Errno 2] File b'FileName.csv' does not exist: b'FileName.csv'

In [ ]:
import pandas as pd
product_sellingData = pd.read_csv('FileName.csv',index_col = 1)
print(product_sellingData)
